version: "2"

services: 
  resume:
    build: .
    image: yelpcamp
    ports:
      - 80:8080
    volumes:
      - ./app:/app
    depends_on: 
      - resume_db 
  resume_db:
    image: mongo:4.2.8
    volumes:
      - db: /data/db
      - config: /data/configdb

